Dockerfile, README.md, azure-pipelines-master.yml, azure-pipelines-release.yml
=> Added devops files

.prod/uwsgi.ini, Dockerfile
This PR should make the production image build locally and with the pipeline.
Refs ATV-10
=> ATV-10 | Build production image

atv/exceptions.py, atv/settings.py, documents/api/viewsets.py, documents/models.py, documents/serializers/attachment.py, documents/serializers/document.py, documents/tests/test_api_create_document.py, documents/tests/test_api_patch_document.py, documents/tests/test_api_retrieve_attachment.py, documents/tests/test_api_retrieve_document.py, utils/exceptions.py
* Add an error handler for API errors to have a common format with clear messages for the clients
* The error messages can be translated by defaul with Django i18n when messages are translated
* Add custom exceptions to make errors clearer
The error messages follow the format:
```json
{
"errors": [
{
"code": "GENERAL_ERROR",
"message": "Something went wrong"
}
]
}
```
**[ATV-71](https://helsinkisolutionoffice.atlassian.net/browse/ATV-71):** Improve API messages
```shell
$ pytest
```
Try, for example:
**Fetch an endpoint without proper credentials:**
```
curl --location --request GET 'http://localhost:8000/v1/documents/b513c411-bd30-45a6-b078-88eb373be443'
```
`Status code: 403`
```json
{
"errors": [
{
"message": "You do not have permission to perform this action.",
"code": …
```
=> ATV-71 | Improve error messages

atv/exceptions.py, documents/api/viewsets.py, documents/consts.py, documents/tests/snapshots/snap_test_api_patch_document.py, documents/tests/test_api_patch_document.py
* Only allow owners to update the document's metadata, content, draft, and attachments
**[ATV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/ATV-XXX):** 
Requires that the following PRs are merged first:
#34 
```shell
$ pytest documents/tests/test_api_patch_document.py
```
=> ATV-24 | Update owner document

Dockerfile, scripts/setup_user.sh, scripts/wait-for-it.sh
This PR changes the Dockerfile base image to Red Hat UBI for Python.
- Security updates for images are handled by Red Hat
- Images have been tested for usage in OpenShift
**[ATV-55](https://helsinkisolutionoffice.atlassian.net/browse/ATV-55):** Change Dockerfile to use a Red Hat base image
=> ATV-55 | Use Red Hat base image for Python

atv/decorators.py, atv/tests/test_decorators.py, documents/api/viewsets.py, documents/tests/test_api_create_attachment.py, documents/tests/test_api_list_documents.py, documents/tests/test_api_patch_document.py, documents/tests/test_models.py, documents/tests/test_serializers.py, services/tests/conftest.py, services/tests/test_signals.py, services/tests/test_utils.py, services/tests/utils.py, services/utils.py, users/tests/conftest.py, utils/test/test_exceptions.py, utils/uuid.py
* Add a bunch of tests and fix some things that I noticed when adding the tests
```shell
$ pytest
```
=> Add a bunch of tests and fix some things

audit_log/viewsets.py
**[ATV-118](https://helsinkisolutionoffice.atlassian.net/browse/ATV-118): Audit Logging logs internal IP instead of requesters IP address**
=> ATV-118 Exclude private IP addresses from audit logging

.prod/uwsgi.ini
Update config to ignore write errors
Reduce number of processes since no performance improvements were observed
**[ATV-124](https://helsinkisolutionoffice.atlassian.net/browse/ATV-124): Fix OS write errors** 
No 
No
=> ATV-124 Fix OS write errors

audit_log/audit_logging.py, audit_log/enums.py, audit_log/tests/snapshots/snap_test_audit_logging.py, audit_log/tests/test_audit_logging.py, audit_log/viewsets.py, documents/api/viewsets.py, documents/tests/snapshots/snap_test_api_patch_document.py, documents/tests/snapshots/snap_test_api_retrieve_document.py, documents/tests/test_api_create_attachment.py, documents/tests/test_api_destroy_attachment.py, documents/tests/test_api_destroy_document.py, documents/tests/test_api_list_documents.py, documents/tests/test_api_patch_document.py, documents/tests/test_api_retrieve_attachment.py, documents/tests/test_api_retrieve_document.py
Multiple fixes and improvements
**[ATV-139](https://helsinkisolutionoffice.atlassian.net/browse/ATV-139): Prevent document and related attachment deletion if document deletable is false** 
**[ATV-137](https://helsinkisolutionoffice.atlassian.net/browse/ATV-137): Make audit log events more useful** 
**[ATV-136](https://helsinkisolutionoffice.atlassian.net/browse/ATV-137): GDPR API delete request creates two audit log events instead of one** 
Yes
yes
=> Feature fixes and improvements

atv/authentication.py
Cache verified API-key for 5 minutes per verification to improve performance of subsequent requests
Improves performance of subsequent requests within 5 minutes of API key verification
**[ATV-141](https://helsinkisolutionoffice.atlassian.net/browse/ATV-141): Improve API key performance** 
No
Yes
=> ATV-141 API-key caching

documents/api/viewsets.py, documents/serializers/document.py, documents/tests/test_api_patch_document.py, users/models.py
**[ATV-142](https://helsinkisolutionoffice.atlassian.net/browse/ATV-142): Don't save names or emails to user table** 
**[ATV-143](https://helsinkisolutionoffice.atlassian.net/browse/ATV-143): Allow changing document owner with API key authentication** 
**[ATV-145](https://helsinkisolutionoffice.atlassian.net/browse/ATV-145): Usernames follow helusers format** 
Yes
Yes
[ATV-142]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATV-143]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATV-145]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-145?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> Fix user usage

documents/api/docs.py, documents/serializers/status_history.py, requirements-dev.txt, requirements.txt
update vulnerable packages and fix documentation
**[ATV-162](https://helsinkisolutionoffice.atlassian.net/browse/ATV-162): Update vulnerable dependencies** 
**[ATV-163](https://helsinkisolutionoffice.atlassian.net/browse/ATV-163): Fix documentation** 
No
Yes
[ATV-162]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATV-163]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Feature update dependencies

atv/settings.py
Add setting for sentry log level
**[ATV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/ATV-XXX):**
=> ATV-175 Sentry logging level env variable

requirements.txt
New version is causing issues
**[ATV-XXX](https://helsinkisolutionoffice.atlassian.net/browse/ATV-XXX):**
=> ATV-175 Downgrade sentry from 1.40.0 to 1.24.0

.commitlintrc.json, .github/workflows/py-coding-style.yml, .pre-commit-config.yaml
Adds commitlint. Also updates flake and isort hooks.
Refs RATY-106
=> chore: add commitlint

atv/urls.py, requirements-dev.txt, requirements.txt
=> deps: upgrade dependencies

Dockerfile
**[ATV-188](https://helsinkisolutionoffice.atlassian.net/browse/ATV-188):** 
[ATV-188]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: run app error ATV-188

.git-blame-ignore-revs, README.md
=> chore: add .git-blame-ignore-revs

atv/settings.py
Add support for multiple IDP providers
Co-PR: https://dev.azure.com/City-of-Helsinki/atv/_git/atv-pipelines/pullrequest/10653
refs: hp-2481
=> fix: add tunnistus support

atv/settings.py
Use latest CORS variable naming convention from: https://pypi.org/project/django-cors-headers/
**[ATV-189](https://helsinkisolutionoffice.atlassian.net/browse/ATV-189)**
[ATV-189]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATV-189: Update CORS variable naming
