atv/settings.py
atv/urls.py
requirements.in
requirements.txt
services/api.py
services/permissions.py
services/tests/conftest.py
services/tests/test_api_authentication.py

This PR adds initial permission check for the `ServiceAPIKey` model.
- Adds `HasServiceAPIKey` permission class
- Initial dummy documents API
- Use `X-Api-Key` header for the API key

ATV-2 | Add permission check for the ServiceAPIKey

---

atv/settings.py

When building the production image `FIELD_ENCRYPTION_KEYS` is not available. This broke the build when static assets were being collected.
Refs ATV-1

Fix building production image

---

Dockerfile

Mount point (in production) seems to have read+write+execute for all parties.
Also it looks like the file permissions in OpenShift env behave normally i.e. folder permissions (for /srv/atv) are replaced by the permissions from the mount, so the same Dockerfile trick doesn't work.
From production:

ATV-1 | Mount /srv/atv doesn't require permission trick in Dockerfile

---

documents/serializers/document.py
documents/tests/test_api_create_document.py

When submitting a new document without file attachments, the serializer
tried to check for file limits and pop the data from the original
validated data. Because no files were uploaded, the value was None, and
it was failing the check for max uploads and later when popping them
from the data.
* Add checks so that the `attachment` field has a default value to avoid `None`s
**[ATV-54](https://helsinkisolutionoffice.atlassian.net/browse/ATV-54):** Fix Document attachment upload
Closes Sentry error [ATV-API-8](https://sentry.io/share/issue/c5a240c36b884cada5bb683b9ec7f0dd/)
```bash
pytest documents/tests/test_api_create_document.py::test_create_document_no_attachments
```
```bash
curl --location --request POST 'http://localhost:8000/v1/documents/' \
--header 'X-Api-Key: <YOUR-API-KEY>' \ …
```

Validate that posted attachments are not None

---

atv/settings.py

Changing permissions will result in an error since the file mount (in production) enforces permissive permissions by default (777). Due to the permissive default permissions we should be able to just skip the permission change.
**[ATV-53](https://helsinkisolutionoffice.atlassian.net/browse/ATV-53):** Fix file volume permissions
- [Sentry bug](https://sentry.io/organizations/city-of-helsinki/issues/2585083468/?project=5826284)

ATV-53 | Don't change uploaded file permissions

---

documents/serializers/document.py
documents/tests/snapshots/snap_test_api_create_document.py
documents/tests/test_api_create_document.py

The Document create endpoint does not support submitting the `content`, which is the main reason of the service, so without it the whole Document is useless. This fix adds the `content` to the serializers to allow saving it. 
**[ATV-1](https://helsinkisolutionoffice.atlassian.net/browse/ATV-1):** As an anonymous user, I want to submit a public RFI, to obtain a public document
#10 
```shell
$ pytest documents/tests/test_api_create_document.py
```
```shell
curl --location --request POST 'http://localhost:8000/v1/documents/' \
--header 'X-Api-Key: YOUR-API-KEY' \
--form 'business_id="1234567-8"' \
--form 'transaction_id="34b9f4b4c9774ff8b2fa0827b2ace014"' \
--form 'tos_function_id="c1f23d3a9eea4b43829cba5a68401799"' \
--form 'tos_record_id="ba3cb4fabe9b45f48d04db0a4422bf41"' \
--form …
```

ATV-1 | Add content input for Document creation

---

atv/decorators.py
documents/api.py
documents/serializers/__init__.py
documents/serializers/attachment.py
documents/serializers/document.py
documents/tests/snapshots/snap_test_api_patch_document.py
documents/tests/test_api_patch_document.py
requirements-dev.in
requirements-dev.txt
utils/tests.py

* Add support for updating documents with PATCH request
* Remove some redundant checks from the POST Document
**[ATV-63](https://helsinkisolutionoffice.atlassian.net/browse/ATV-63):** Add PATCH functionality for document metadata
Requires that #15 is merged first
```shell
$ pytest documents/tests/test_api_patch_document.py
```
For now, this has to be done through the browser, since it requires the Django login for authentication

ATV-63 | Document update endpoint

---

atv/settings.py
atv/urls.py
documents/api/__init__.py
documents/api/docs.py
documents/api/viewsets.py
documents/serializers/attachment.py
requirements.in
requirements.txt

* Add documentation for the existing functionality on the API
**[ATV-68](https://helsinkisolutionoffice.atlassian.net/browse/ATV-68):** Add swagger documentation for live environment
Open the API url:
http://localhost:8000/v1/schema/swagger-ui/#/
For better control of what's displayed, the `documents/api/docs.py` adds the same documentation as the [original API](https://app.swaggerhub.com/apis/klempine/transactions-storage/v1#/), same error codes and descriptions. The functionalities which are not implemented yet are commented, and the ones that will not be implemented are just excluded.

ATV-68 | Add Swagger documentation for the live functionalities

---

atv/settings.py
documents/api/docs.py
documents/api/filtersets.py
documents/api/viewsets.py
documents/tests/snapshots/snap_test_api_create_document.py
documents/tests/test_api_create_document.py
documents/tests/test_api_list_documents.py
utils/api.py

* Add filter options by `status`, `type`, `businessId`, `userId`, and `transactionId`
* Add a search option for `metadata` contents
* Allow sorting the results by `created_at` and `updated_at`
The full spec of the API can be found here: https://app.swaggerhub.com/apis/klempine/transactions-storage/v1#/default/get_documents
**[ATV-64](https://helsinkisolutionoffice.atlassian.net/browse/ATV-64):** Add filter/sorting options for Document list
```shell
$ pytest documents/tests/test_api_list_documents.py::test_list_document_filter
$ pytest documents/tests/test_api_list_documents.py::test_list_document_sorting
```
According to the Documents you have on your environment, try either of the filter parameters as query params, e.g.
```
http://localhost:8000/v1/documents/?type=application
```
From …

ATV-64 | Add filtering, sorting, and paginating for Documents

---

atv/exceptions.py
audit_log/viewsets.py
documents/api/viewsets.py
documents/models.py
documents/serializers/document.py
documents/tests/test_api_create_document.py
documents/tests/test_api_list_documents.py
documents/tests/test_api_patch_document.py

Add audit logging for `AttachmentViewSet` and `DocumentViewSet`.
**[ATV-51](https://helsinkisolutionoffice.atlassian.net/browse/ATV-51):** Implement Audit Logging
Requires #18

ATV-51 | Add audit logging to ModelViewSets

---

documents/api/viewsets.py
documents/tests/conftest.py
documents/tests/factories.py
documents/tests/test_api_attachment_detail.py
documents/tests/test_api_create_document.py
documents/tests/test_api_list_documents.py

* Add staff checks for attachments
**[ATV-62](https://helsinkisolutionoffice.atlassian.net/browse/ATV-62):** Add the permission checking for Staff users
```shell
$ pytest documents/tests/test_api_attachment_detail.py
```

ATV-62 | Add staff checks for attachments

---

documents/admin.py
documents/api/viewsets.py
documents/tests/test_api_list_documents.py
users/models.py

* Allow for authenticated users to fetch their own documents
* The filter for allowed Docuemnts is done on the `get_queryset` level, so when the `list` method is called, it only allows for the specific subset of Documents plus the `login_required`
* Add small tweaks to Django Admin to make it easier which user is associated to a lease
**[ATV-37](https://helsinkisolutionoffice.atlassian.net/browse/ATV-37):** As an authenticated user I want to filter and sort my diploma copy requests to find a specific request easily
* https://helsinkisolutionoffice.atlassian.net/browse/ATV-36
* #15 
* #20

ATV-37 | Fetch Documents for authenticated users

---

atv/decorators.py
documents/api/viewsets.py
documents/tests/snapshots/snap_test_api_create_document.py
documents/tests/test_api_create_document.py
services/utils.py

* Modify `DocumentViewSet` to allow creating authenticated Documents
* When the user is not authenticated, it tries creating the document anonymously with the Service API key. If no key is found, then a 403 status is returned
**[ATV-19](https://helsinkisolutionoffice.atlassian.net/browse/ATV-19):** As an authenticated user I want to submit a diploma copy request, to obtain a copy of my diploma
#10 
```shell
$ pytest documents/tests/test_api_create_document.py
```
Testing manually is a bit complex at the moment, since we don't have the JWT authentication in place yet. The way to do it would be to login with a valid user which has been assigned to a permission group for a `Service`, so that the `ServiceMiddleware` can determine the correct Service.
With that user, then send the POST request …

ATV-19 | Create authenticated Documents

---

atv/decorators.py
documents/api/viewsets.py
documents/tests/test_api_list_documents.py

* Add better tests for this functionality
* Fix queryset to filter **both** user and service
**[ATV-21](https://helsinkisolutionoffice.atlassian.net/browse/ATV-21):** As an authenticated user I want to see a list of my diploma copy requests, to see the requests' status and information
```shell
$ pytest documents/tests/test_api_list_documents.py
```
The other two open PRs have to be merged first
#27
#28

ATV-21 | Authenticated user documents

---

documents/api/viewsets.py
documents/tests/snapshots/snap_test_api_retrieve_document.py
documents/tests/test_api_retrieve_document.py

* Add check for permissions of Document details
**[ATV-22](https://helsinkisolutionoffice.atlassian.net/browse/ATV-22):** As an authenticated user I want to see a diploma copy request's details and attachments, to verify what I submitted
```shell
$ pytest documents/tests/test_api_retrieve_document.py
```
* Requires that #31 is merged first

ATV-22 | User can see own documents

---

atv/exceptions.py
documents/api/docs.py
documents/api/viewsets.py
documents/tests/test_api_destroy_document.py

* Add functionality and checks for deleting documents
* Add `locked_after` details to the error message
* Update the API documentation to match the changes
**[ATV-21](https://helsinkisolutionoffice.atlassian.net/browse/ATV-21):** 
Requires that the following PR merged first:
#31 
```shell
$ pytest documents/tests/test_api_destroy_document.py
```

ATV-23 | Remove Documents

---

documents/api/docs.py
documents/api/viewsets.py
documents/tests/test_api_destroy_attachment.py

* Add functionality to remove Attachments
* Update the API documentation to match the changes
**[ATV-25](https://helsinkisolutionoffice.atlassian.net/browse/ATV-25):** As an authenticated user I want to remove an attachment from my diploma copy request draft to get rid of a wrong attachment
Requires that this PRs are merged first:
#31 
#33 
```shell
$ pytest documents/tests/test_api_destroy_attachment.py
```
* Only owners are allowed to remove them, in this case `staff` can't

ATV-25 | Remove Attachment

---

atv/exceptions.py
documents/api/docs.py
documents/api/querysets.py
documents/api/viewsets.py
documents/tests/snapshots/snap_test_api_create_attachment.py
documents/tests/test_api_create_attachment.py
documents/tests/test_api_destroy_attachment.py
documents/tests/test_api_destroy_document.py
documents/tests/test_api_patch_document.py
services/utils.py

* Add create method for creating Attachment for Documents
* Only allowed for the owners of the Document, staff is not allowed
**[ATV-26](https://helsinkisolutionoffice.atlassian.net/browse/ATV-26):** As an authenticated user I want to add an attachment to my diploma copy request draft to provide a necessary file with the request
```
$ pytest documents/tests/test_api_create_attachment.py
```
```
curl --location --request POST 'http://localhost:8000/v1/documents/a9e542d3-35f9-4841-a8f9-22bfd0e15001/attachments/' \
--header 'Authorization: Bearer <YOUR_TOKEN>' \
--header 'Content-Type: image/jpeg' \
--header 'Content-Disposition: attachment; filename="<YOUR_FILENAME>"' \
--data-binary '@/path/to/your/file.jpg'
```
The file to be uploaded has to be sent as a

ATV-26 | Create Attachment for Documents

---

audit_log/admin.py
audit_log/audit_logging.py
audit_log/tests/snapshots/snap_test_audit_logging.py
audit_log/tests/test_audit_logging.py

Audit log didn't include the user UUID. Audit logging was incorrectly checking from the `target` which field should be used for logging the `actor`.
**[ATV-83](https://helsinkisolutionoffice.atlassian.net/browse/ATV-83):** Audit log uses actor.pk instead of actor.uuid in message
```
$ pytest audit_log/tests/test_audit_logging.py
```
Access a document from the API as authenticated user and observe that `audit_event.actor.user_id` includes the user UUID.

ATV-83 | Add user UUID properly to an audit log

---

atv/decorators.py
documents/api/viewsets.py
documents/tests/test_api_methods_not_allowed.py

* Raise a `405 Method Not Allowed` when getting the `documents-attachments-list`
* Add tests for the methods that should raise a 405
**[ATV-82](https://helsinkisolutionoffice.atlassian.net/browse/ATV-82):** Document's attachments endpoint returns all attachments for user
```shell
$ pytest documents/tests/test_api_methods_not_allowed.py
```
Any random uuid as document ID will work:
```
curl --location --request GET 'http://localhost:9000/v1/documents/b513c411-bd30-45a6-b078-88eb373be442/attachments/' \
--header 'Authorization: Bearer <YOUR_TOKEN>'
```

ATV-82 | Restrict Document's Attachment list

---

atv/decorators.py
atv/urls.py
documents/api/docs.py
documents/api/filtersets.py
documents/api/querysets.py
documents/api/viewsets.py
documents/serializers/document.py
documents/tests/test_api_retrieve_document.py

API for fetching documents specific to a single user without including sensitive information
Tests for API
Updated docs
This API allows filtering through documents of a single user throughout all services without revealing sensitive information withing the documents to allow easier collaboration of different services. 
**[ATV-77](https://helsinkisolutionoffice.atlassian.net/jira/software/c/projects/ATV/boards/207?modal=detail&selectedIssue=ATV-77): As a user I want to view the metadata of my documents in across services** 
Yes

ATV-77 Document metadata API

---

atv/exceptions.py
atv/settings.py
docker-compose.yml
documents/serializers/attachment.py
documents/tests/test_api_create_attachment.py
documents/tests/test_api_create_document.py
documents/tests/test_api_patch_document.py
documents/utils.py
requirements.in
requirements.txt

Add error response for detected malware
Add clamav config to docker-compose.yml
Add clamav host settings
Fix failing tests when running tests without clamav connection
Support for clamav virus scanning within the cluster
**[ATV-95](https://helsinkisolutionoffice.atlassian.net/browse/ATV-95):Virus scan incoming files**
Edited tests to mock clamav scan
Manually tested scanner response to malware (EICAR test file)
Running without docker in dev environment requires installing clamav locally

ATV-95 Virus scan incoming files

---

Dockerfile

Add --allowerasing argument to update to fix incompatible packages
**[ATV-116](https://helsinkisolutionoffice.atlassian.net/browse/ATV-116): Fix dockerfile to prevent pipeline build failure** 
Tested build process in local environment after reproducing bug

ATV-116 Fix Dockerfile to prevent pipeline build failure

---

documents/api/docs.py
documents/api/viewsets.py
documents/tests/test_api_destroy_document.py

Change delete response status to HTTP 200 from 204 due to response having a body Fix and Improve documentation
Fix test
Bug fix
**[ATV-134](https://helsinkisolutionoffice.atlassian.net/browse/ATV-134): Fix GDPR API delete response status code** 
Yes
Yes

ATV-134 Fix GDPR API delete response status

---

atv/settings.py
atv/urls.py
documents/api/docs.py
documents/api/viewsets.py

Add sentry-debug url which always causes an error that is sent to sentry Add setting and environment variable for sentry debugging
Minor fixes
Fix statistics api incorrect 403 when not authenticated Fix missing fields in api docs
**[ATV-169](https://helsinkisolutionoffice.atlassian.net/browse/ATV-169): Add url for sentry debugging** 
No
Yes
[ATV-169]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-169 Add sentry debugging url

---

documents/api/docs.py
documents/api/filtersets.py

Sometimes icontains returns irrelevant results due to words containing each other
make metadata filtering exact
**[ATV-174](https://helsinkisolutionoffice.atlassian.net/browse/ATV-174): Change lookfor filter to use iexact instead of icontains** 
Yes
[ATV-174]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-174 Update lookfor filter to use iexact instead of icontains

---

documents/fields.py

Override get_db_prep_save to create a json formatted string instead of psycopg2 Json object
Content has to be saved in exactly the same way as before Django update to maintain data integrity
**[ATV-172](https://helsinkisolutionoffice.atlassian.net/browse/ATV-172): Fix content format when saving to DB** 
No
Yes
[ATV-172]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-172 Fix content formatting when saving to db

---

documents/api/docs.py
documents/api/viewsets.py
documents/tests/snapshots/snap_test_api_patch_document.py
documents/tests/snapshots/snap_test_api_retrieve_document.py
documents/tests/test_api_list_documents.py

Add endpoint for fetching multiple documents per id Add tests for endpoint
Update test snapshots
Update docs
Allows fetching multiple specified documents at once.
**[ATV-176](https://helsinkisolutionoffice.atlassian.net/browse/ATV-176): Document batch list** 
Yes
Yes
Swagger docs are incomplete
[ATV-176]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-176 Document batch list

---

documents/api/viewsets.py
documents/tests/test_api_destroy_attachment.py

Add permission check to allow deletion of attachment with special permission
Updated test case
User with assigned permission should be able to delete both any document or attachment from their service.
**[ATV-179](https://helsinkisolutionoffice.atlassian.net/browse/ATV-179): Can't delete undeletable attachment with special permission** 
Yes
Yes
[ATV-179]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-179 Fix Attachment deletion with permission

---

requirements-dev.txt
requirements.in
requirements.txt

Lock sentry version to 1.24.0
Update vulnerable dependencies
**[ATV-178](https://helsinkisolutionoffice.atlassian.net/browse/ATV-178): Update dependencies** 
Yes
[ATV-178]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATV-178 Update Django and Black versions

---

documents/api/viewsets.py
documents/models.py
documents/tests/test_api_destroy_document.py

Remove metadata from documents when performing ~GPDR~ GDPR delete.
**[ATV-213](https://helsinkisolutionoffice.atlassian.net/browse/ATV-213)**
Add an assert to an existing test.
[ATV-213]: https://helsinkisolutionoffice.atlassian.net/browse/ATV-213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove metadata on GDPR delete
